from pathlib import Path

p=Path('app/main.py')
s=p.read_text()

old='''@app.get(f"{router_prefix}/windows-agents/package/msi")\ndef windows_agent_msi_package(agent=Depends(_agent_auth)):'''
new='''@app.delete(f"{router_prefix}/windows-agents/{agent_id}/purge")\ndef windows_agent_purge(agent_id: int, request: Request, user=Depends(require_admin)):\n    with db() as c:\n        row=c.execute("SELECT * FROM windows_agents WHERE id=?",(agent_id,)).fetchone()\n        if not row: raise HTTPException(404,"Windows Agent not found")\n        if not row["revoked_at"] and row["status"] != "revoked":\n            raise HTTPException(409,"Revoke the Windows Agent before removing it permanently")\n        sessions=[r[0] for r in c.execute("SELECT id FROM windows_remote_sessions WHERE agent_id=?",(agent_id,)).fetchall()]\n        finding_ids=[r[0] for r in c.execute("SELECT id FROM event_findings WHERE agent_id=?",(agent_id,)).fetchall()]\n        if sessions:\n            marks=",".join("?" for _ in sessions)\n            c.execute(f"DELETE FROM windows_remote_events WHERE session_id IN ({marks})",sessions)\n        c.execute("DELETE FROM windows_remote_sessions WHERE agent_id=?",(agent_id,))\n        c.execute("DELETE FROM windows_agent_rechecks WHERE agent_id=?",(agent_id,))\n        c.execute("DELETE FROM windows_agent_commands WHERE agent_id=?",(agent_id,))\n        findings_deleted=0\n        if finding_ids:\n            findings_deleted=len(_delete_event_findings(c,finding_ids))\n        c.execute("DELETE FROM windows_agents WHERE id=?",(agent_id,))\n        audit(c,user["username"],"windows_agent_purged",str(agent_id),json.dumps({"computer_name":row["computer_name"],"findings_deleted":findings_deleted,"remote_sessions_deleted":len(sessions)}),client_ip(request))\n    return {"ok":True,"computer_name":row["computer_name"],"findings_deleted":findings_deleted,"remote_sessions_deleted":len(sessions)}\n\n@app.get(f"{router_prefix}/windows-agents/package/msi")\ndef windows_agent_msi_package(agent=Depends(_agent_auth)):'''
if old not in s: raise SystemExit('backend anchor missing')
s=s.replace(old,new,1)

old="""async function revokeWindowsAgent(id){\n const x=WINDOWS_AGENTS.find(a=>a.id===id);if(!confirm(`Revoke ${x?.computer_name||'this Windows Agent'}? The installed agent will no longer be able to upload events.`))return;\n try{await json('/api/v1/windows-agents/'+id,{method:'DELETE'});await loadWindowsAgents()}catch(e){alert('Could not revoke Windows Agent: '+e.message)}\n}\n"""
new=old+"""async function purgeWindowsAgent(id){\n const x=WINDOWS_AGENTS.find(a=>a.id===id);if(!x)return;\n if(!x.revoked_at&&x.status!=='revoked'){alert('Revoke this Windows Agent before removing it permanently.');return}\n if(!confirm(`Permanently remove ${x.computer_name||x.hostname||'this computer'} from GODSEYE?\\n\\nThis removes the revoked agent record, its Event Findings, remote-session history, queued commands, and rechecks. Linked tickets remain as history. This cannot be undone.`))return;\n try{const r=await json('/api/v1/windows-agents/'+id+'/purge',{method:'DELETE'});alert(`Removed ${r.computer_name||'computer'} from GODSEYE. ${r.findings_deleted||0} Event Finding(s) removed.`);await loadWindowsAgents();await loadEventFindings();if(typeof loadRemoteAccess==='function')await loadRemoteAccess()}catch(e){alert('Could not permanently remove Windows Agent: '+e.message)}\n}\n"""
if old not in s: raise SystemExit('revoke JS anchor missing')
s=s.replace(old,new,1)

old="""${x.revoked_at?'':`<button class=\"secondary admin-only\" onclick=\"configureWindowsAgent(${x.id})\">Configure</button><button class=\"danger admin-only\" onclick=\"revokeWindowsAgent(${x.id})\">Revoke</button>`}"""
new="""${x.revoked_at?`<button class=\"danger admin-only\" onclick=\"purgeWindowsAgent(${x.id})\">Remove Permanently</button>`:`<button class=\"secondary admin-only\" onclick=\"configureWindowsAgent(${x.id})\">Configure</button><button class=\"danger admin-only\" onclick=\"revokeWindowsAgent(${x.id})\">Revoke</button>`}"""
if old not in s: raise SystemExit('agent modal action anchor missing')
s=s.replace(old,new,1)

old="""else action=`<button class=\"secondary remote-connect\" type=\"button\" disabled>Offline</button>`;return `<div class=\"remote-agent-row\"><div class=\"remote-agent-main\"><div class=\"remote-agent-name\"><span class=\"remote-dot ${on?'online':'offline'}\"></span>${esc(a.computer_name||a.hostname||('Agent '+a.id))}</div><div class=\"remote-agent-sub\">${esc(a.ip_address||'No IP')} · Agent ${esc(a.agent_version||'unknown')} · ${esc(a.os_version||'Windows')}</div></div>${action}</div>`"""
new="""else action=`<button class=\"secondary remote-connect\" type=\"button\" disabled>Offline</button>`;if(a.revoked_at||a.status==='revoked')action=`<button class=\"danger admin-only\" type=\"button\" onclick=\"purgeWindowsAgent(${a.id})\">Remove</button>`;return `<div class=\"remote-agent-row\"><div class=\"remote-agent-main\"><div class=\"remote-agent-name\"><span class=\"remote-dot ${on?'online':'offline'}\"></span>${esc(a.computer_name||a.hostname||('Agent '+a.id))}</div><div class=\"remote-agent-sub\">${esc(a.ip_address||'No IP')} · Agent ${esc(a.agent_version||'unknown')} · ${esc(a.os_version||'Windows')}</div></div>${action}</div>`"""
if old not in s: raise SystemExit('remote action anchor missing')
s=s.replace(old,new,1)

p.write_text(s)
Path('VERSION').write_text('4.26.0\n')
Path('tests/test_v426_remove_revoked_computers.py').write_text('''from pathlib import Path\n\ndef test_v426_version_and_revoked_agent_purge_contract():\n    assert Path("VERSION").read_text().strip()=="4.26.0"\n    src=Path("app/main.py").read_text()\n    assert 'windows-agents/{agent_id}/purge' in src\n    assert 'def windows_agent_purge' in src\n    assert 'Revoke the Windows Agent before removing it permanently' in src\n    assert 'DELETE FROM windows_remote_sessions WHERE agent_id=?' in src\n    assert 'DELETE FROM windows_agent_rechecks WHERE agent_id=?' in src\n    assert 'DELETE FROM windows_agent_commands WHERE agent_id=?' in src\n    assert '_delete_event_findings(c,finding_ids)' in src\n    assert 'windows_agent_purged' in src\n\ndef test_v426_ui_exposes_permanent_remove_in_both_agent_portals():\n    src=Path("app/main.py").read_text()\n    assert 'async function purgeWindowsAgent(id)' in src\n    assert 'Remove Permanently' in src\n    assert 'onclick=\\"purgeWindowsAgent(${a.id})\\">Remove</button>' in src\n    assert 'await loadEventFindings()' in src\n    assert "if(typeof loadRemoteAccess==='function')await loadRemoteAccess()" in src\n''')
