from pathlib import Path


def replace(path, old, new):
    p = Path(path)
    text = p.read_text(encoding='utf-8')
    if old not in text:
        raise SystemExit(f'expected text not found in {path}: {old[:120]!r}')
    p.write_text(text.replace(old, new), encoding='utf-8', newline='\n')

svc = 'windows/agent-x64/src/Godseye.WindowsAgent/GodseyeAgentService.cs'

replace(svc,
'''        const uint INVALID_SESSION_ID = 0xFFFFFFFF;\n        const uint CREATE_UNICODE_ENVIRONMENT = 0x00000400;''',
'''        const uint INVALID_SESSION_ID = 0xFFFFFFFF;\n        const uint CREATE_UNICODE_ENVIRONMENT = 0x00000400;\n        const uint LOGON_WITH_PROFILE = 0x00000001;''')

replace(svc,
'''        [DllImport("Wtsapi32.dll", SetLastError=true)] static extern bool WTSQueryUserToken(uint SessionId, out IntPtr phToken);\n        [DllImport("Wtsapi32.dll", CharSet=CharSet.Unicode, SetLastError=true)] static extern bool WTSSendMessage(IntPtr hServer, int SessionId, string pTitle, int TitleLength, string pMessage, int MessageLength, int Style, int Timeout, out int pResponse, bool bWait);\n        [DllImport("advapi32.dll", CharSet=CharSet.Unicode, SetLastError=true)] static extern bool CreateProcessAsUser(IntPtr hToken, string lpApplicationName, System.Text.StringBuilder lpCommandLine, IntPtr lpProcessAttributes, IntPtr lpThreadAttributes, bool bInheritHandles, uint dwCreationFlags, IntPtr lpEnvironment, string lpCurrentDirectory, ref STARTUPINFO lpStartupInfo, out PROCESS_INFORMATION lpProcessInformation);''',
'''        [DllImport("Wtsapi32.dll", SetLastError=true)] static extern bool WTSQueryUserToken(uint SessionId, out IntPtr phToken);\n        [DllImport("Wtsapi32.dll", CharSet=CharSet.Unicode, SetLastError=true)] static extern bool WTSSendMessage(IntPtr hServer, int SessionId, string pTitle, int TitleLength, string pMessage, int MessageLength, int Style, int Timeout, out int pResponse, bool bWait);\n        [DllImport("userenv.dll", SetLastError=true)] static extern bool CreateEnvironmentBlock(out IntPtr lpEnvironment, IntPtr hToken, bool bInherit);\n        [DllImport("userenv.dll", SetLastError=true)] static extern bool DestroyEnvironmentBlock(IntPtr lpEnvironment);\n        [DllImport("advapi32.dll", CharSet=CharSet.Unicode, SetLastError=true)] static extern bool CreateProcessAsUser(IntPtr hToken, string lpApplicationName, System.Text.StringBuilder lpCommandLine, IntPtr lpProcessAttributes, IntPtr lpThreadAttributes, bool bInheritHandles, uint dwCreationFlags, IntPtr lpEnvironment, string lpCurrentDirectory, ref STARTUPINFO lpStartupInfo, out PROCESS_INFORMATION lpProcessInformation);\n        [DllImport("advapi32.dll", CharSet=CharSet.Unicode, SetLastError=true)] static extern bool CreateProcessWithTokenW(IntPtr hToken, uint dwLogonFlags, string lpApplicationName, System.Text.StringBuilder lpCommandLine, uint dwCreationFlags, IntPtr lpEnvironment, string lpCurrentDirectory, ref STARTUPINFO lpStartupInfo, out PROCESS_INFORMATION lpProcessInformation);''')

replace(svc,
'''            string kind = request != null && request.ContainsKey("kind") ? Convert.ToString(request["kind"]) : "";\n            if (String.Equals(kind,"capture",StringComparison.OrdinalIgnoreCase))''',
'''            string kind = request != null && request.ContainsKey("kind") ? Convert.ToString(request["kind"]) : "";\n            if (String.Equals(kind,"ping",StringComparison.OrdinalIgnoreCase)) return new Dictionary<string,object>{{"ok",true},{"ready",true}};\n            if (String.Equals(kind,"capture",StringComparison.OrdinalIgnoreCase))''')

old_launch = '''        void LaunchRemoteHelper(string pipeName, string requestedBy, uint sessionId)\n        {\n            IntPtr token=IntPtr.Zero; if(!WTSQueryUserToken(sessionId,out token))throw new Exception("Could not obtain the signed-in Windows user token ("+Marshal.GetLastWin32Error()+").");\n            try\n            {\n                string exe=Environment.ProcessPath; if(String.IsNullOrWhiteSpace(exe))throw new Exception("Agent executable path is unavailable."); requestedBy=(requestedBy??"administrator").Replace("\\\"","'");\n                var cmd=new System.Text.StringBuilder("\\\""+exe+"\\\" --remote-helper \\\""+pipeName+"\\\" \\\""+requestedBy+"\\\" --consent-granted"); STARTUPINFO si=new STARTUPINFO();si.cb=Marshal.SizeOf(typeof(STARTUPINFO));si.lpDesktop=@"winsta0\\default"; PROCESS_INFORMATION pi;\n                if(!CreateProcessAsUser(token,exe,cmd,IntPtr.Zero,IntPtr.Zero,false,CREATE_UNICODE_ENVIRONMENT,IntPtr.Zero,Path.GetDirectoryName(exe),ref si,out pi))throw new Exception("Could not launch the interactive GODSEYE helper ("+Marshal.GetLastWin32Error()+").");\n                remoteHelperProcessId=(int)pi.dwProcessId; CloseHandle(pi.hThread);CloseHandle(pi.hProcess);\n            }\n            finally{if(token!=IntPtr.Zero)CloseHandle(token);}\n        }'''

new_launch = '''        void LaunchRemoteHelper(string pipeName, string requestedBy, uint sessionId)\n        {\n            IntPtr token=IntPtr.Zero;\n            if(!WTSQueryUserToken(sessionId,out token)) throw new Exception("Could not obtain the signed-in Windows user token ("+Marshal.GetLastWin32Error()+").");\n            IntPtr environment=IntPtr.Zero;\n            try\n            {\n                string exe=Environment.ProcessPath;\n                if(String.IsNullOrWhiteSpace(exe)) throw new Exception("Agent executable path is unavailable.");\n                requestedBy=(requestedBy??"administrator").Replace("\\\"","'");\n                if(!CreateEnvironmentBlock(out environment,token,false))\n                {\n                    Log("Remote helper environment block could not be created ("+Marshal.GetLastWin32Error()+"); continuing with the Windows token environment.");\n                    environment=IntPtr.Zero;\n                }\n                STARTUPINFO si=new STARTUPINFO();\n                si.cb=Marshal.SizeOf(typeof(STARTUPINFO));\n                si.lpDesktop=@"winsta0\\default";\n                PROCESS_INFORMATION pi;\n                var cmd=new System.Text.StringBuilder("\\\""+exe+"\\\" --remote-helper \\\""+pipeName+"\\\" \\\""+requestedBy+"\\\" --consent-granted");\n                bool created=CreateProcessAsUser(token,exe,cmd,IntPtr.Zero,IntPtr.Zero,false,CREATE_UNICODE_ENVIRONMENT,environment,Path.GetDirectoryName(exe),ref si,out pi);\n                int createAsUserError=created?0:Marshal.GetLastWin32Error();\n                if(!created)\n                {\n                    cmd=new System.Text.StringBuilder("\\\""+exe+"\\\" --remote-helper \\\""+pipeName+"\\\" \\\""+requestedBy+"\\\" --consent-granted");\n                    created=CreateProcessWithTokenW(token,LOGON_WITH_PROFILE,exe,cmd,CREATE_UNICODE_ENVIRONMENT,environment,Path.GetDirectoryName(exe),ref si,out pi);\n                }\n                if(!created) throw new Exception("Could not launch the interactive GODSEYE helper. CreateProcessAsUser="+createAsUserError+", CreateProcessWithTokenW="+Marshal.GetLastWin32Error()+".");\n                remoteHelperProcessId=(int)pi.dwProcessId;\n                if(pi.hThread!=IntPtr.Zero)CloseHandle(pi.hThread);\n                if(pi.hProcess!=IntPtr.Zero)CloseHandle(pi.hProcess);\n                Log("Remote helper launched in Windows session "+sessionId+" as process "+remoteHelperProcessId+".");\n            }\n            finally\n            {\n                if(environment!=IntPtr.Zero)DestroyEnvironmentBlock(environment);\n                if(token!=IntPtr.Zero)CloseHandle(token);\n            }\n        }'''
replace(svc, old_launch, new_launch)

replace(svc,
'''        Dictionary<string,object> RemoteHelperRequest(string pipeName, Dictionary<string,object> request, int timeout=3000)\n        {\n            using(NamedPipeClientStream pipe=new NamedPipeClientStream(".",pipeName,PipeDirection.InOut,PipeOptions.None))\n            { pipe.Connect(timeout); using(StreamReader reader=new StreamReader(pipe,Encoding.UTF8,false,8192,true)) using(StreamWriter writer=new StreamWriter(pipe,new UTF8Encoding(false),8192,true){AutoFlush=true}) { writer.WriteLine(Json.Serialize(request)); string line=reader.ReadLine(); if(String.IsNullOrWhiteSpace(line))throw new Exception("Remote helper returned no response."); return Json.Deserialize<Dictionary<string,object>>(line); } }\n        }''',
'''        Dictionary<string,object> RemoteHelperRequest(string pipeName, Dictionary<string,object> request, int timeout=3000)\n        {\n            using(NamedPipeClientStream pipe=new NamedPipeClientStream(".",pipeName,PipeDirection.InOut,PipeOptions.None))\n            { pipe.Connect(timeout); using(StreamReader reader=new StreamReader(pipe,Encoding.UTF8,false,8192,true)) using(StreamWriter writer=new StreamWriter(pipe,new UTF8Encoding(false),8192,true){AutoFlush=true}) { writer.WriteLine(Json.Serialize(request)); string line=reader.ReadLine(); if(String.IsNullOrWhiteSpace(line))throw new Exception("Remote helper returned no response."); return Json.Deserialize<Dictionary<string,object>>(line); } }\n        }\n\n        void WaitForRemoteHelperReady(string pipeName, int timeoutMs=15000)\n        {\n            DateTime deadline=DateTime.UtcNow.AddMilliseconds(timeoutMs);\n            Exception last=null;\n            while(DateTime.UtcNow<deadline)\n            {\n                if(remoteHelperProcessId>0)\n                {\n                    try\n                    {\n                        using(Process p=Process.GetProcessById(remoteHelperProcessId))\n                        {\n                            if(p.HasExited) throw new Exception("Interactive GODSEYE helper exited during startup with code "+p.ExitCode+".");\n                        }\n                    }\n                    catch(ArgumentException){throw new Exception("Interactive GODSEYE helper exited before it became ready.");}\n                }\n                try\n                {\n                    Dictionary<string,object> pong=RemoteHelperRequest(pipeName,new Dictionary<string,object>{{"kind","ping"}},750);\n                    if(pong!=null&&pong.ContainsKey("ok")&&Convert.ToBoolean(pong["ok"]))\n                    {\n                        Log("Remote helper readiness handshake completed.");\n                        return;\n                    }\n                }\n                catch(Exception ex){last=ex;}\n                Thread.Sleep(250);\n            }\n            throw new Exception("Interactive GODSEYE helper did not become ready within "+timeoutMs+" ms"+(last==null?".":": "+last.Message));\n        }''')

replace(svc,
'''            remoteStop=false; remoteSessionId=sessionId; remotePipeName="GODSEYE-Remote-"+sessionId+"-"+Guid.NewGuid().ToString("N");\n            LaunchRemoteHelper(remotePipeName,requestedBy,windowsSessionId);\n            remoteWorker=new Thread(()=>RemoteSessionLoop(cfg,sessionId,remotePipeName)){IsBackground=true,Name="GODSEYE Remote Support"}; remoteWorker.Start();''',
'''            remoteStop=false; remoteSessionId=sessionId; remotePipeName="GODSEYE-Remote-"+sessionId+"-"+Guid.NewGuid().ToString("N");\n            try\n            {\n                LaunchRemoteHelper(remotePipeName,requestedBy,windowsSessionId);\n                WaitForRemoteHelperReady(remotePipeName);\n                Log("Remote support request "+sessionId+" approved; interactive helper is ready.");\n            }\n            catch(Exception ex)\n            {\n                try { Post(cfg,"/api/v1/windows-agents/remote/sessions/"+sessionId+"/state",new Dictionary<string,object>{{"status","failed"},{"error",ex.Message}},ReadApiKey()); } catch {}\n                StopRemoteSession();\n                throw;\n            }\n            remoteWorker=new Thread(()=>RemoteSessionLoop(cfg,sessionId,remotePipeName)){IsBackground=true,Name="GODSEYE Remote Support"}; remoteWorker.Start();''')

# Bump all source/install/test metadata that still pins 2.2.2.
for path in [
    'windows/agent-x64/src/Godseye.WindowsAgent/Godseye.WindowsAgent.csproj',
    'windows/agent-x64/installer/msi/Package.wxs',
    'windows/agent-x64/installer/GODSEYE-Agent-x64.iss',
    'tests/test_permanent_x64_windows_agent_v423.py',
    'tests/test_remote_access_v4231.py',
    'tests/test_windows_agent_self_update.py',
]:
    p=Path(path)
    text=p.read_text(encoding='utf-8')
    if '2.2.2' in text:
        p.write_text(text.replace('2.2.2','2.2.3'),encoding='utf-8',newline='\n')

# Add regression checks to the Remote Access test.
p=Path('tests/test_remote_access_v4231.py')
text=p.read_text(encoding='utf-8')
needle='''    assert 'MOUSEEVENTF_WHEEL' in src\n'''
extra='''    assert 'MOUSEEVENTF_WHEEL' in src\n    assert 'CreateEnvironmentBlock' in src and 'CreateProcessWithTokenW' in src\n    assert 'WaitForRemoteHelperReady' in src and '\"kind\",\"ping\"' in src\n'''
if needle in text and 'WaitForRemoteHelperReady' not in text:
    text=text.replace(needle,extra)
p.write_text(text,encoding='utf-8',newline='\n')

print('Applied Agent 2.2.3 remote handoff reliability fix.')
